### PR TITLE
Refactor populator methods into instance methods.

### PR DESCRIPTION
**Pull request by shioyama**
Currently the populator class is just used as a place to store a bunch of class methods, but it really should be an instance which is iniated with a variant. This adds a few lines of code but I think makes more sense.

### CODE REVIEW

**Comment by degicat** [comment]
@camelmasa Please review this.

**Comment by camelmasa** [comment]
@shioyama LGTM :+1: 

Why do we need to set mysql version :question:  Could you add the reason to last commit's description :question: 

Then, we'll merge it :+1:

**Comment by shioyama** [comment]
@camelmasa about mysql, I'm actually not totally sure, see: https://travis-ci.org/degica/spree-license-key/jobs/84237423

Setting the version fixed it... and I didn't dig deeper. Any idea?

**Comment by camelmasa** [comment]
@shioyama No, I haven't idea. It seems complecated problem because it depending spree's files.
like `spree/core/testing_support/common_rake`.

We'll merge it. We are goting to create other PR for fixing if we want it in the future.

**Comment by shioyama** [comment]
@camelmasa my thoughts exactly. Ok I'll merge this, thanks!

**Pull request merged**
